> @Author  : Lewis Tian (taseikyo@gmail.com)
>
> @Link    : github.com/taseikyo
>
> @Range   : 2020-11-15 - 2020-11-21

# Weekly #3

[readme](../README.md) | [previous](202011W2.md) | [next](202011W4.md)

![](../images/lala-azizli-OFZUaeYKP3k-unsplash.jpg "Books you should definitely read")

\**Photo by Lala Azizli on Unsplash*

## Table of Contents

- [algorithm](#algorithm-)
	- 922.按奇偶排序数组 II
- [review](#review-)
- [tip](#tip-)
	- Python 异常处理之 try/except/else/finally（中文）
	- Python yield from（StackOverflow）
	- Python async/await 入门指南（中文）
- [share](#share-)

## algorithm [⬆](#weekly-3)

### 1. [922.按奇偶排序数组 II](https://leetcode-cn.com/problems/sort-array-by-parity-ii/)

20/11/12 的每日一题，对数组进行排序，以便当 A[i] 为奇数时，i 也是奇数；当 A[i] 为偶数时，i 也是偶数。

题目不难，首先建一个跟原数组同样大的数组，用两个变量标记当前奇偶的下标，遍历原数组，依次将数据填入返回数组中。本来是用 C++ 实现的，然后又用 Go 实现了一遍，区别并不大，只不过有些语法不太熟，需要查一下才知道怎么用。

```Go
func sortArrayByParityII(A []int) []int {
	ret := make([]int, len(A))
	even_idx, odd_idx := 0, 1
	for _, x := range(A)  {
		if x % 2 == 0 {
			ret[even_idx] = x
			even_idx += 2
		} else {
			ret[odd_idx] = x
			odd_idx += 2
		}
	}
	return ret
}
```

## review [⬆](#weekly-3)

## tip [⬆](#weekly-3)

### 1. [Python 异常处理之 try/except/else/finally（中文）](https://blog.csdn.net/m0_37822685/article/details/80259402)

之前都是无脑 `try...except...`，今天来看看其他的用法。

1. try - except

```Python
try:
	print("Before error")
	a = b
	print(a)
	print("After error")
except:
	print("Error")

print("Continue!")

# Before error
# Error
# Continue!
```

所以流程如下：

- 先执行 try block，直到发现了错误，不再执行异常之后的代码
- 执行 except block
- 向下继续

对于多个 except，则会依次匹配错误，如果没有匹配到程序会报错，所以可以最后加一个通用匹配。像下面如果没有最后一个 except 程序会报错：

```Python
try:
	a = b
	print(a)
except SyntaxError:
	print("<<<< SyntaxError")
except SystemExit:
	print("<<<< NameError")
except:
	print("I don't know, but error.")

print("He, try/except is so difficult!")

# I don't know, but error.
# He, try/except is so difficult!
```

2. try - except - else

```Python
try:
	a = b
	print(a)
except SyntaxError:
	print("<<<< SyntaxError")
except SystemExit:
	print("<<<< NameError")
except:
	print("I don't know, but error.")
else:
	print("That's good, no error.")

print("He, try/except is so difficult!")

# I don't know, but error.
# He, try/except is so difficult!
```

可见，有异常时，else block 时不执行的。

```Python
try:
	b = 1
	a = b
	print(a)
except SyntaxError:
	print("<<<< SyntaxError")
except SystemExit:
	print("<<<< NameError")
except:
	print("I don't know, but error.")
else:
	print("That's good, no error.")

print("He, try/except is so difficult!")

# 1
# That's good, no error.
# He, try/except is so difficult!
```

可见，无异常时 else block 执行。

3. try - finally

无论 try 语句是否有异常，最后都要执行的代码。

```Python
try:
	b = 1
	a = b
	print(a)
except SyntaxError:
	print("<<<< SyntaxError")
except SystemExit:
	print("<<<< NameError")
except:
	print("I don't know, but error.")
else:
	print("That's good, no error.")
finally:
	print("I will be here!")

print("He, try/except is so difficult!")

# 1
# That's good, no error.
# I will be here!
# He, try/except is so difficult!
```

```Python
try:
	a = b
	print(a)
except SyntaxError:
	print("<<<< SyntaxError")
except SystemExit:
	print("<<<< NameError")
except:
	print("I don't know, but error.")
else:
	print("That's good, no error.")
finally:
	print("I will be here!")

print("He, try/except is so difficult!")

# I don't know, but error.
# I will be here!
# He, try/except is so difficult!
```

### 2. [Python `yield from`（StackOverflow）](https://stackoverflow.com/a/26109157/7669794)

很棒的一个回答，详细地介绍了 `yield from` 的作用，如果只是简单使用，可以把他当作是对于迭代器的展开（`yield from iterator` == `for v in iterator: yield v`），但是它不仅仅如此，它在调用者与子生成器之间构建了一个透明的双向联系（*establishes a transparent bidirectional connection between the caller and the sub-generator*），只不过这个关键词字面意思并没有表现出来罢了。

另外使用 `yield from` 可以从生成器中读取/向生成器发送数据（双向），而且它自动完成了异常向子生成器的传递。

```Python
class SpamException(Exception):
    pass

def writer():
    while True:
        try:
            w = (yield)
        except SpamException:
            print('***')
        else:
            print('>> ', w)

def writer_wrapper(coro):
    yield from coro

w = writer()
wrap = writer_wrapper(w)
wrap.send(None)  # "prime" the coroutine
for i in [0, 1, 2, 'spam', 4]:
    if i == 'spam':
        wrap.throw(SpamException)
    else:
        wrap.send(i)

# >>  0
# >>  1
# >>  2
# ***
# >>  4
```

建议去看原回答，写得很详细。

### 3. [Python async/await 入门指南（中文）](https://zhuanlan.zhihu.com/p/27258289)

看懂了前半部分，后面就看不懂了 @-@，异步编程还是太复杂了，可能写一些简单的东西会很简单，一旦涉及更深的东西就很复杂了。

## share [⬆](#weekly-3)

[readme](../README.md) | [previous](202011W2.md) | [next](202011W4.md)
